name: Goals Deployment
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BACKEND_IMAGE: goals_backend
  FRONTEND_IMAGE: goals-frontend
  AWS_REGION: eu-north-1
  TASK_DEF_FILE_BACKEND: task-definition-backend.json
  TASK_DEF_FILE_FRONTEND: task-definition-frontend.json
  backend_container: goals_backend
  service_Name_backend: goals_task-service
  Cluster_Name_backend: goals-cluster


jobs:
  build_backend:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
      IS_RELEASE: ${{ steps.vars.outputs.IS_RELEASE }}


    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Detect version
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "IS_RELEASE=true" >> $GITHUB_OUTPUT

          else
            VERSION="dev-${GITHUB_SHA::7}" 
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
            echo "IS_RELEASE=false" >> $GITHUB_OUTPUT
          
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: ${{ steps.vars.outputs.IS_RELEASE == 'true' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}${{ steps.vars.outputs.IS_RELEASE == 'true' && ':latest' || '' }}

            ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ steps.vars.outputs.VERSION }}
            

  build_frontend:
    needs: build_backend
    runs-on: ubuntu-latest


    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          build-args: |
            REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL}}
          push: ${{ needs.build_backend.outputs.IS_RELEASE == 'true' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}${{ needs.build_backend.outputs.IS_RELEASE == 'true' && ':latest' || '' }}

            ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:${{ needs.build_backend.outputs.VERSION }}

  deploy_backend_to_AWS:
    runs-on: ubuntu-latest
    needs:
      - build_backend

    if: ${{ needs.build_backend.outputs.IS_RELEASE == 'true' }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Login to Aws
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Render new task definition for backend
        id: backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.TASK_DEF_FILE_BACKEND }}
          container-name: ${{ env.backend_container }}
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:${{ needs.build_backend.outputs.VERSION }}


      - name: Deploy backend to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.backend.outputs.task-definition }}
          service: ${{ env.service_Name_backend }}
          cluster: ${{ env.Cluster_Name_backend }}
          wait-for-service-stability: true
